name: Deploy Calculator

on:
  push:
    tags:
      - "calculator/v*"

jobs:

  deploy:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore NuGet Packages
      run: nuget restore ProCalculator/ProCalculator.sln

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build the application
      run: msbuild ProCalculator/ProCalculator.sln /t:publish /p:RuntimeIdentifier=win-x64 /p:Configuration=Release

    - uses: csexton/release-asset-action@v2
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: ProCalculator/bin/Release/ProCalculator.exe
          
