name: Deploy Calculator

on:
  push:
    tags:
      - "calculator/v*"

jobs:

  deploy:
    permissions: write-all
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore NuGet Packages
      run: nuget restore .\ProCalculator\ProCalculator.sln

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build the application
      run: msbuild ProCalculator/ProCalculator.csproj /p:Configuration=Release /p:RuntimeIdentifier=win-x64

    - name: Create Release
      id: create_release
    # You may pin to the exact commit or the version.
    # uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5
      uses: ncipollo/release-action@v1.13.0

    - name: Upload Assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ProCalculator/bin/Release
