name: Deploy Calculator

on:
  push:
    tags:
      - "calculator/v*"

jobs:

  deploy:
    permissions: write-all
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore NuGet Packages
      run: nuget restore .\ProCalculator\ProCalculator.sln

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build the application
      run: msbuild ProCalculator/ProCalculator.csproj /p:Configuration=Release /p:RuntimeIdentifier=win-x64

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
      
    - name: Upload Release Asset
      uses: csexton/release-asset-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pattern: ProCalculator/bin/Release/ProCalculator.exe
        release-url: ${{ steps.create_release.outputs.upload_url }}
